### ISSUE TITLE
Feature: Allow specifying css class per row, per cell

### ISSUE THREAD

**Issue by fuzzthink** [dritter/extended-table#7]
@dritter Thank you so much for such a great table library. I've looked at all table libraries for Svelte, and this is the best one. I have no idea why you aren't getting the traffic like others.

One feature I see lacking is there isn't a way to add css classes per row or cell other than using slots. It is extremely helpful if that is possible. One eg. of how I see they can be specified is introducing an optional `rows` prop that is declared similar to `columns` and `className` spec on columns props.

```javascript
const data = [{
  value: 'a',
  count: 1,
  css: 'danger', // className on tr (row) specified
}, {
  value: 'b',
  count: 5,
  css: { count: 'success' }, // className on td (cell) specified
}, ...rest]

// new rows props spec
const rows = [{
    propertyPath: 'css',
    className: 'red', // optional value string or function for className on tr. If omitted, the value obtained via propertyPath is taken
}, ...otherRowsSpec]

const columns = [{ 
    title: 'Count', 
    propertyPath: 'count',
    className: { // new cell props spec
        propertyPath: 'css',
        value: (val) => val==='success' ? 'green' : "", // optional value string or function for className on td.
        // Just like for rows, if omitted, the value obtained via propertyPath is taken.
    }
}, ...otherColsSpec]
```

I would be thrilled if this is possible and believe others may be as well. Let me know what you think.

**Comment by dritter** [comment]
Hey @fuzzthink !

Thanks for your kind words. Made my day :)

First off:
I am sure you saw that I tried to make all columns and rows selectable. Every row is either `row-even` or `row-odd`, and `col-even`/`col-odd` and a sluggified propertyPath (e.g. `col-location_postcode`; all non-alphanumerical characters are replaced by underscores) on every column. Same goes for column heads (propertyPaths prefixed with `col-head-`).

The reason I did it this way is to avoid complexity and minimise propertyPath resolutions. Or at least moves the complexity from JavaScript to CSS (e.g. targeting single cells `tr:nth-of-type(4)  .col-last_name`). But I see that this solution is suboptimal. Guessing from your example you want to dynamically set classes based on certain conditions instead of targeting cells statically..

**Comment by fuzzthink** [comment]
Yes, odd/even and col-wise styling isn't too useful for me. Right now, I do row lv styling via a hack by adding a single char col and post-render styling by adding class to the row based on the char of that col. Cell lv styling is done by parsing for values. Features like my proposal will enable me to get rid of these hacks.

**Comment by dritter** [comment]
Alright. Thanks for your input. I'll try to put up a prototype for that in the next couple days.

**Comment by fuzzthink** [comment]
One (simpler) alternative is to forget about specification in rows and columns props and just take some metadata in the data, like using a leading underscore `_class` as https://github.com/fouita/svelte-tw-data-table does.

The example may still be good, that row-level data specifies the row (tr) classNames and nested path specifies the cell (td) classNames.
```js
const data = [{
  value: 'a',
  count: 1,
  _class: 'danger', // className on tr (row) specified
}, {
  value: 'b',
  count: 5,
  _class: { count: 'success' }, // className on td (cell) specified
}, ...rest]
```

**Comment by dritter** [comment]
TBH I like your initial suggestion better, because having a special key on the data would mean that you have to preprocess the  data to write the CSS classes, and even that may be not enough, so you have to add `className`s on the column definition as well. That definition and data are pretty far away from each other..
